dist: bionic
language: node_js
addons:
  apt:
    update: 'true'
    packages:
      - libsystemd-dev
jobs:
  include:
    - stage: test
      node_js:
        - 14.1.0
      script:
        - npm run cover
        - npx codecov
        - cat ./build/coverage/lcov.info | npx coveralls
      after_failure:
        - journalctl --user -xe
    - stage: doc
      node_js: lts/*
      skip_cleanup: 'true'
      script:
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        script:
          - npx semantic-release
        cleanup: 'false'
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - /^mkpr/.*$/
    - /^npm-template-sync/.*$/
matrix:
  include:
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64
